# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.advntrsblazor_credentials }}

    - name: Build Docker Image
      run: |
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        docker build . --tag myblazor:latest

    # - name: Build app
    #   run: docker run --mount type=bind,source=${GITHUB_WORKSPACE},target=/app myblazor:latest dotnet build --configuration Release /app

    - name: Publish app
      run: docker run --mount type=bind,source=${GITHUB_WORKSPACE},target=/app myblazor:latest dotnet publish -c Release -r linux-x64 -o /app/advntrsblazor /app

    # - name: Test app
    #   run: docker run --mount type=bind,source=${GITHUB_WORKSPACE},target=/app myblazor:latest dotnet test --no-restore --verbosity normal /app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: blazorArtifacts
        path: ./advntrsblazor

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: advntrsblazor
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: ./advntrsblazor

    # Azure logout
    - name: logout
      run: |
        az logout